image: node:latest

pages:
  script:
    - yarn
    - yarn add gatsby-cli
    - node_modules/.bin/gatsby build
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master
