image: node:latest

cache:
  paths:
    - node_modules/
pages:
  script:
    - npm install
    - npm install gatsby-cli
    - ./node_modules/.bin/gatsby build
  artifacts:
    paths:
      - public
  only:
    - master
