image: node:latest

pages:
  script:
    - npm install
    - npm install gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master
