image: node:latest

pages:
  script:
    - yarn
    - yarn add gatsby-cli
    - export NODE_OPTIONS=--openssl-legacy-provider
    - node_modules/.bin/gatsby build 

  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master
